name: Run Web Automation Tests

on:
  push:
    branches: [ main ]

jobs:
  run-selenium-tests:
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Checkout Code
      uses: actions/checkout@v3

    - name: ☕ Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '11'

    - name: 🧰 Install Maven
      run: sudo apt-get install -y maven

    - name: 🧪 Run Tests with Maven
      run: mvn clean test
